
const Discord = require('discord.js');
const Twana1 = new Discord.Client();
const Twana2 = new Discord.Client();
const Twana3 = new Discord.Client();
const Twana4 = new Discord.Client();
const Twana5 = new Discord.Client();
const Twana6 = new Discord.Client();
const Twana7 = new Discord.Client();
const Twana8 = new Discord.Client();
const Twana9 = new Discord.Client();
const Twana10 = new Discord.Client();
const Twana11 = new Discord.Client();
const Twana12 = new Discord.Client();
const Twana13 = new Discord.Client();
const Twana14 = new Discord.Client();
const Twana15 = new Discord.Client();
const Twana16 = new Discord.Client();
const Twana17 = new Discord.Client();
const Twana18 = new Discord.Client();
const Twana19 = new Discord.Client();
const Twana20 = new Discord.Client();
const Twana21 = new Discord.Client();
const Twana22 = new Discord.Client();
const Twana23 = new Discord.Client();
const Twana24 = new Discord.Client();
const Twana25 = new Discord.Client();
const Twana26 = new Discord.Client();
const Twana27 = new Discord.Client();
const Twana28 = new Discord.Client();
const Twana29 = new Discord.Client();
const Twana30 = new Discord.Client();
const Twana31 = new Discord.Client();
const Twana32 = new Discord.Client();
const Twana33 = new Discord.Client();
const Twana34 = new Discord.Client();
const Twana35 = new Discord.Client();
const Twana36 = new Discord.Client();
const Twana37 = new Discord.Client();
const Twana38 = new Discord.Client();
const Twana39 = new Discord.Client();
const Twana40 = new Discord.Client();
const Twana41 = new Discord.Client();
const Twana42 = new Discord.Client();
const Twana43 = new Discord.Client();
const Twana44 = new Discord.Client();
const Twana45 = new Discord.Client();
const Twana46 = new Discord.Client();
const Twana47 = new Discord.Client();
const Twana48 = new Discord.Client();
const Twana49 = new Discord.Client();
const Twana50 = new Discord.Client();
const Twana51 = new Discord.Client();
const Twana52 = new Discord.Client();
const Twana53 = new Discord.Client();
const Twana54 = new Discord.Client();
const Twana55 = new Discord.Client();
const Twana56 = new Discord.Client();
const Twana57 = new Discord.Client();
const Twana58 = new Discord.Client();
const Twana59 = new Discord.Client();
const Twana60 = new Discord.Client();
const Twana61 = new Discord.Client();
const Twana62 = new Discord.Client();
const Twana63 = new Discord.Client();
const Twana64 = new Discord.Client();
const Twana65 = new Discord.Client();
const Twana66 = new Discord.Client();
const Twana67 = new Discord.Client();
const Twana68 = new Discord.Client();
const Twana69 = new Discord.Client();
const Twana70 = new Discord.Client();
const Twana71 = new Discord.Client();
const Twana72 = new Discord.Client();
const Twana73 = new Discord.Client();
const Twana74 = new Discord.Client();
const Twana75 = new Discord.Client();
const Twana76 = new Discord.Client();
const Twana77 = new Discord.Client();
const Twana78 = new Discord.Client();
const Twana79 = new Discord.Client();
const Twana80 = new Discord.Client();
const Twana81 = new Discord.Client();
const Twana82 = new Discord.Client();
const Twana83 = new Discord.Client();
const Twana84 = new Discord.Client();
const Twana85 = new Discord.Client();
const Twana86 = new Discord.Client();
const Twana87 = new Discord.Client();
const Twana88 = new Discord.Client();
const Twana89 = new Discord.Client();
const Twana90 = new Discord.Client();
const Twana91 = new Discord.Client();
const Twana92 = new Discord.Client();
const Twana93 = new Discord.Client();
const Twana94 = new Discord.Client();
const Twana95 = new Discord.Client();
const Twana96 = new Discord.Client();
const Twana97 = new Discord.Client();
const Twana98 = new Discord.Client();
const Twana99 = new Discord.Client();
const Twana100= new Discord.Client();



Twana1.login("OTUzNTc5MTAxMDY1NzI4MDkz.YjHMLA.T78KNULWVyHOgzvKBtCk6_AhpEc");
Twana2.login("OTUzNTU0MDEyOTc0Nzc2MzMw.YjHMOw.AvfsMwfhk3iF2Tc9pLmEaFc9-7s");
Twana3.login("OTUzNTc5NDIxMzAwODQyNDk2.YjHMTA.wvgFDT9nM4okmavy4Gh8Q9Z37lo");
Twana4.login("OTUzNTc5NzQ1NTU0MDc5NzU0.YjHMWw.Zg761M-jnh6V_mfW7RChzds_RFw");
Twana5.login("OTUzNTgwMDY2OTM4NDQ5OTMw.YjHMbQ.vYSTo1OAZ5U3qpsDyQwCTrm8XnQ");
Twana6.login("OTUzNTgwNTkyMjk1OTk3NDQx.YjHMfQ.jAQXW30fD2YrTmopkGmiizbFRLU");
Twana7.login("OTUzNTgwOTAyODY3NDMxNDQ4.YjHMiw.t-MdrXVbld0fg01IwL-COYB2wYg");
Twana8.login("OTUzNTgxMzEwNTQ5NTU3MjQ5.YjHMmA.H0A6aVshKotnGetGaFCdaS2VEx0");
Twana9.login("OTUzNTgxNjQwNjcwNjY2Nzcz.YjHMpw.D2Hg6JzHNjnbwm50zNlwiEZPhjw");
Twana10.login("OTUzNTgxOTc4NjYwMjQ5NjQw.YjHMtQ.d9E5xumP22fdrKUyJ5mCJAi-big");
Twana11.login("OTUzNTgyMjg0MjE5NDk4NTE3.YjHMxA.2FZBl0__s0PY6YQVB8ZJNGtGab0");
Twana12.login("OTUzNTgyNjIzMTkwNTUyNTc2.YjHM1Q.daf0-PvRqpARUGlO7aIwtUSrRPg");
Twana13.login("OTUzNTgzMDQ1OTc2NDIwMzYy.YjHM4Q.Ma5FBtiglfxoLo4XyiitnIRXYpQ");
Twana14.login("OTUzNTgzNzA1MzQ2MTQ2MzE1.YjHM7Q.XyiEjnt7JmG7oWUb4UdqbT-PyTo");
Twana15.login("OTUzNTg0MDIxMDMwNDQ1MDc2.YjHM-w.4v224EIyQ30Ixn6UPcS1sj3lwic");
Twana16.login("OTUzNTg0MzgyNzI2Mjc1MTE0.YjHNCQ.WOkw4Meh4UcRnw8hbnRBFcE7Rm4");
Twana17.login("OTUzNTg0NzUxOTgwMTk1ODkw.YjHNFA.kwoP-Huw0NfiTw-CqwTeZ0NUmw0");
Twana18.login("OTUzNTg1NDUyNzcyOTA5MDU2.YjHNIA.0W5MyCJLCM16yh3jn9fwwJBBcCU");
Twana19.login("OTUzNTg1MDg2MzgzNjY5MjU4.YjHNKw.wrumL-aC3DiNfvvjm9iFxvuM2BM");
Twana20.login("OTUzNTg1NzM3Njg3Nzg5NjM4.YjHNNg.js0xkVEIU42hSwq57j_9-SwWW8U");
Twana21.login("OTUzNTg2MTAwOTg1ODIzMjMz.YjHNQQ.RMl8fSuDen4iD89IBxEzJEpYsAY");
Twana22.login("OTUzNTg2NDM5MzAyNTY5OTk0.YjHNTw.G_kp3dYknNYKh9muTGwGJ7yfW7A");
Twana23.login("OTUzMzcyMjc1MjIxMDkwMzU0.YjHNZw.-08CPTwvKYHq5cWNFVsL-Tgcmic");
Twana24.login("OTUzMzcyNzU4NDM4NDU3MzY0.YjHNcw.eixSzEnX5Lsj0dd4IBoUEY4I2qs");
Twana25.login("OTUzMzczMDg3NzIwNjg1NjEx.YjHNfg.2w-qNB62bPiPN1Kl4BYECq4J-xU");
Twana26.login("OTUzMzczNDMxMjg4NzI1NTY1.YjHNiw.cW--_LONO0UgYRbByvPicEHEWjw");
Twana27.login("OTUzMzczODQwOTA4NjQ0Mzcy.YjHNmA.fG9QnicUuShzasIvdTtf_aDFcf8");
Twana28.login("OTUzMzc0MzAwNjY3MjU2ODQy.YjHNow.wkUCv5Bz50fyLzEJ_WVDQLq2SaY");
Twana29.login("OTUzMzc0Nzc5NTcyOTA4MDUy.YjHNrw.0rI_o0rJgpzrUdHzsfLWNSaY30w");
Twana30.login("OTUzNTM2NTkxMjk1NTQ5NTAw.YjHNug.60_mD2S4QPBzPHisvMQnscOMcdg");
Twana31.login("OTUzNTM3MDU4NjE2NTI4OTI2.YjHNxA.A-YEWYs3jUmSQg_sQM2paIexndI");
Twana32.login("OTUzNTM3NTAyMjIyODg4OTcx.YjHNzw.a0QPtDnQbK75HHLQY8ztj9LymKY");
Twana33.login("OTUzNTM3ODU5OTQ2Njk2NzY0.YjHN2g.O1TKUSOJBEmP0h8yvHXE17L3g2g");
Twana34.login("OTUzNTM4MTk3MTEwMDAxNzI1.YjHN6g.73MBoCSNV8kaUzzi76YtHxS2LHI");
Twana35.login("OTUzNTM4NTU0MjYzMzgwMDIx.YjHN9g.v7kcku0arH9OlCTR5yiJ2wrzlYs");
Twana36.login("OTUzNTM5MDg2NDc0NDI4NDE2.YjHOAw.tbHKoXalxhHv-IouAjtYSa76F9A");
Twana37.login("OTUzNTM5NTA0MDkyODcyNzI0.YjHODw.7_-J6ZkJAmbOpOdWyWcUeLWagQc");
Twana38.login("OTUzNTM5ODU0MzA4ODgwMzg0.YjHOGg.zB-x_TgE6ra-cdL_LRlq9ETp8qg");
Twana39.login("OTUzNTQwMTY0Njc0Nzg1MzAx.YjHOJg.aO1m3o0jgnkwuJkj70uidZsvk-A");
Twana40.login("OTUzNTQwNTM3OTI1OTIyODE3.YjHOMQ.juYNZf4w4j4WCovpZuv4wcz-9fo");
Twana41.login("OTUzNTQwOTM3ODk4OTM0Mjkz.YjHOPQ.QmMq5ocnoZKKqNmShFZrVwsjH5Q");
Twana42.login("OTUzNTQxNDg4MzA0ODY5Mzg2.YjHOSQ.mY2PEZSpSdJ20a708Xjbc7DBgYA");
Twana43.login("OTUzMzUyODQ0NjEyODgyNTUx.YjHOyg.BQ14gDC7uCkxEDXV62zPeGDCKZk");
Twana44.login("OTUzMzUzMjUyODM2MDk4MDgy.YjHO1w.qADSQDyv21NZzOyrlePGiNNXF4Q");
Twana45.login("OTUzMzUzNjAwODI0OTI2MjQx.YjHO5w.GstcSxqqm-jz3w-YUlgGhJGigOI");
Twana46.login("OTUzMzUzOTg3MzgwMzc5NzU4.YjHO9g.q86p1QZWS1K49Kt8dTtVv8WFrr8");
Twana47.login("OTUzMzU0ODI0Mzg3MjcyODA1.YjHPFg.SupeYOBXslWYdU0tn-IG4enWf7A");
Twana48.login("OTUzMzU1MTk0MDkwMDAwNDY0.YjHPJA.XLRaIMNLMiwNtjulzQFxdSIv4L4");
Twana49.login("OTUzMzU1NTYzMjY0Mjc4NTQ4.YjHPMQ.BghmgPtzK7xsZi-qShHZ4jhCe_U");
Twana50.login("OTUzMzU5NDMwMTgxODU1MzUz.YjHPPQ.u84lMQXiSxbcqvydaV7oLlNPYyc");
Twana51.login("OTUzMzU5ODI5Mjc0MDY2OTY1.YjHPWA.BH53uGX_O8XZSqlT9wEB6QQZDH8");
Twana52.login("OTUzMzYwMjIwNjE1MjQ1ODQ1.YjHPZQ.ihk_hwXml-MTTCoVCqzYtF6EObE");
Twana53.login("OTUzMzYwNzk1NjYyNjk2NDc5.YjHPcA.tWDwq3UjQQTmzRjA82yeDew2XbE");
Twana54.login("OTUzMzYxMTk3NDY4NjQ3NTA1.YjHPew.ViJZnjdZxmIZbn5TA5XbtR7JJ6A");
Twana55.login("OTUzMzYxNTUyOTk4ODIxOTA5.YjHPhg.UKPXT5eUV7ndg0__ZEwa1z91fNA");
Twana56.login("OTUzMzYxODkxODczNDExMTE0.YjHPkQ.AtBS_3T3oQDHmitnHKIgjKAJ528");
Twana57.login("OTUzMzYyMjMzNzQyNzQ5NzI2.YjHPnA.aRtjKF75jImQte-bkcK1MJ4NnJU");
Twana58.login("OTUzMzYyNTE0MDY5MDYxNzgy.YjHPsw.0joIZYnYqgWq4XfnPRe-0-goS0s");
Twana59.login("OTUzMzYyOTA1Nzc1MDgzNjIw.YjHPvg.Mx6dBsPHS1DZS37jdsmnD7savOI");
Twana60.login("OTUzMzYzMjgyMjM5MDYyMDg3.YjHPyA.cJcieM7rCiHeqzH8BVYWD1XtFSE");
Twana61.login("OTUzMzYzNjU0NzU2MTYzNjE1.YjHP0w.xuqVhFvPi5of1IyMwoavDSk-DZY");
Twana62.login("OTUzMzYzOTk3MTA3ODM0OTUw.YjHP3g.g0r0aOzb0nGRbRQqQHVu4GV1x0A");
Twana63.login("OTUzMzY0MzE4ODQ0NDg5NzQ4.YjHP6Q.OBRIXvt90mWRj7O_zOh5F4jMw6w");
Twana64.login("OTUzMzY1MjM0Mjg0OTA4NTg0.YjHP9A.k5UaMAspQ7ggWDumj6tRPj0ZtYY");
Twana65.login("OTUzMzcwMTAxNjExMTMwOTQx.YjHP_w.yzllF-R94Kskb6dksYi1zbegEXw");
Twana66.login("OTUzMzcwNTQ0NDkxODU1OTIy.YjHQCg.QRuxvUX0IgHI2mGVbY7Yx2CJuzU");
Twana67.login("OTUzMzcwOTk0NDE0ODU0MjI1.YjHQFw.XAAP-snM66ohYf1rGK-ZR73drP0");
Twana68.login("OTUzMzcxMzU1OTE3NzIxNjcx.YjHQIg.sXJvs1N3ZnZXfpoO1aKiGI8gz9g");
Twana69.login("OTUzMzcxODU3ODkyMDI4NTM2.YjHQMg.RPFDcgWh-XVBVQlsKSmnr_HWlwM");
Twana70.login("OTUzNjQ0MDMzMTc0MDExOTE0.YjHqeA.jE1_v1SkTRdHMDAs6-H99bIvqVc");
Twana71.login("OTUzNjQ0NjU3NTA4Nzc4MDQ0.YjHqhg.cGJ6U1TcI0JMOMVdYOd0baYFwjQ");
Twana72.login("OTUzNjQ1MDQ0ODI3NTcwMTk2.YjHqlA.8-wXBtZcA4UvjOEZr_JBk5FFEG0");
Twana73.login("OTUzNjQ1Mzk5MTU4MTk0MTg2.YjHqnw.OVG_4UnhUopki4V4R3ZpVJ-J8vg");
Twana74.login("OTUzNjQ1NzEyNDk3ODUyNDQ2.YjHqqw.U_rJzEPlJH6J8W7g0Zw2hw7ZDRY");
Twana75.login("OTUzNjQ2MDQ3MDQ4MTM4ODUz.YjHqtg.zP50s7hhvWytW5lcLMzD16BnL1A");
Twana76.login("OTUzNjQ2NDI0OTg4NDc1NTA1.YjHqwA.LoGalStdtSkBr2r4htncAhCe0pQ");
Twana77.login("OTUzNjQ2ODMxMjkwNjg3NTE4.YjHq2g.BAbEVKMfHdwpZj_eQaWMoWvQmsA");
Twana78.login("OTUzNjQ3MTk5Mzg3MDIxMzEy.YjHq5g.zepWoDpKH34Dt-J19ClWj8nvmGo");
Twana79.login("OTUzNjQ3NTk3OTcxNzMwNDUy.YjHq8Q.M90F94zCh7pJStKmwHTVliGAH20");
Twana80.login("OTUzNjQ3OTc1MDY4OTkxNTA4.YjHq_A.VWy8r-tRcp9I3gIzGunJrJEorhY");
Twana81.login("OTUzNjQ4MjYyNjk3NjA3MTY4.YjHrBg.hPK5nCSO2_IbEMcEDJ0hRHSWoSg");
Twana82.login("OTUzNjQ4NDgxNDkzNDY3MTU2.YjHrEw.YFy1S1uF2mmF_t4Qq3zIIv1usd8");
Twana83.login("OTUzNjQ4ODQ1MjYxMjc1MTg2.YjHrIA.mSRzxYwtXcCjITINrLHEtFMiqoE");
Twana84.login("OTUzNjQ5MTM4NTM5NTgxNDcx.YjHrKw.73TTo17zkHkSmbvdfvAYWEL3pkI");
Twana85.login("OTUzNjQ5NDYyMzMxNDczOTIx.YjHrOA.-8PgDnUWK5ZmhY95B0Z20UftQoI");
Twana86.login("OTUzNjQ5ODE2MjcxOTgyNjYy.YjHrRA.cjpeDjvXXArY03LDrKIYislvto0");
Twana87.login("");
Twana88.login("");
Twana89.login("");
Twana90.login("");
Twana91.login("");
Twana92.login("");
Twana94.login("");
Twana95.login("");
Twana96.login("");
Twana97.login("");
Twana98.login("");
Twana99.login("");
Twana100.login("");









